export const RWA_ASSET_CATALOG = [
  {
    id: 'motor-listrik',
    name: 'Ride-Hailing EV Bikes',
    category: 'Mobility',
    segment: 'Phase 1 Eligible',
    assetClass: 'Mobility Assets',
    image: '/ev_ridehailing_surabaya_1777118125456.png',
    description:
      'Productive rental EV bikes for ride-hailing drivers with daily route logs, fixed rental collection, and rent-to-own credit pool eligibility.',
    poolModel: 'Mobility Credit Pool',
    revenueModel: 'Fixed daily rental / rent-to-own installment',
    minimumDeployment: '20-50 verified units',
    proofRequirements: ['Proof of Asset', 'Proof of Activity', 'Proof of Revenue', 'Proof of Maintenance'],
    specs: [
      { label: 'Range per charge', value: '60-120 km' },
      { label: 'Collection model', value: 'Rp 50.000/day' },
      { label: 'Financed cost', value: 'Rp 25.000.000/unit' },
      { label: 'Tenor', value: '36 months' },
      { label: 'Primary proof', value: 'GPS daily route logs' },
    ],
    requirements: ['Operator KYC', 'Asset serial/VIN mapping', 'Phone GPS or telemetry attached', 'Daily collection process', 'Workshop maintenance path'],
  },
  {
    id: 'motor-kargo',
    name: 'Cargo EV Bikes',
    category: 'Mobility',
    segment: 'Phase 1 Eligible',
    assetClass: 'Mobility Assets',
    image: '/ev_logistics_bandung_1777118107682.png',
    description:
      'Cargo EV bikes for last-mile delivery routes with route coverage proofs and recurring operator collections.',
    poolModel: 'Mobility Credit Pool',
    revenueModel: 'Fixed rental or contracted delivery remittance',
    minimumDeployment: '20+ verified units',
    proofRequirements: ['Proof of Asset', 'Proof of Activity', 'Proof of Revenue', 'Proof of Maintenance'],
    specs: [
      { label: 'Range per charge', value: '50-100 km' },
      { label: 'Load capacity', value: '150-200 kg' },
      { label: 'Financed cost', value: 'Rp 25.000.000+/unit' },
      { label: 'Tenor', value: '36 months' },
      { label: 'Primary proof', value: 'Route logs + collection health' },
    ],
    requirements: ['Business KYC', 'Delivery route coverage', 'Telemetry attached', 'Collection reporting', 'Maintenance reserve process'],
  },
  {
    id: 'taxi-van-shuttle',
    name: 'Taxi, Van & Shuttle Fleets',
    category: 'Mobility',
    segment: 'Phase 1B',
    assetClass: 'Mobility Assets',
    image: '/ev_fleet_jakarta_1777118073477.png',
    description:
      'Larger productive fleet assets for contracted people movement and B2B operator remittance models.',
    poolModel: 'Fleet Remittance Pool',
    revenueModel: 'Contracted monthly remittance',
    minimumDeployment: '10+ fleet units with operator contract',
    proofRequirements: ['Proof of Asset', 'Proof of Activity', 'Proof of Revenue', 'Proof of Maintenance'],
    specs: [
      { label: 'Asset type', value: 'Taxi / van / shuttle' },
      { label: 'Revenue source', value: 'Contracted remittance' },
      { label: 'Tenor', value: '36+ months' },
      { label: 'Deployment', value: 'B2B fleet route' },
      { label: 'Primary proof', value: 'Route + remittance checkpoint' },
    ],
    requirements: ['PT/business KYC', 'Fleet contract', 'Telematics active', 'Insurance', 'Operator collection SLA'],
  },
  {
    id: 'charging-hub',
    name: 'Charging & Swap Hubs',
    category: 'Charging',
    segment: 'Future Asset Class',
    assetClass: 'Charging Assets',
    image: '/ev_fleet_tangerang_1777118150818.png',
    description:
      'Depot chargers, swap stations, and corridor charging hubs that can later be financed through metered infrastructure yield pools.',
    poolModel: 'Charging Yield Pool',
    revenueModel: 'Metered kWh / session revenue',
    minimumDeployment: 'Site-level deployment with metering',
    proofRequirements: ['Proof of Asset', 'Proof of Activity', 'Proof of Revenue', 'Proof of Maintenance'],
    specs: [
      { label: 'Metering', value: 'kWh delivered' },
      { label: 'Activity proof', value: 'Charging sessions' },
      { label: 'Revenue source', value: 'Session fees' },
      { label: 'Phase', value: 'Post-MVP' },
      { label: 'Primary proof', value: 'Uptime + kWh meter' },
    ],
    requirements: ['Site contract', 'Metering integration', 'Charger uptime SLA', 'Revenue settlement data', 'Maintenance workflow'],
  },
  {
    id: 'solar-storage',
    name: 'Depot Solar & Battery Storage',
    category: 'Energy',
    segment: 'Future Asset Class',
    assetClass: 'Energy Assets',
    image: '/ev_fleet_tangerang_1777118150818.png',
    description:
      'Solar, storage, and exportable depot energy assets for future energy yield products tied to measured generation and export.',
    poolModel: 'Energy Yield Pool',
    revenueModel: 'kWh generated, stored, or exported',
    minimumDeployment: 'Metered depot energy system',
    proofRequirements: ['Proof of Asset', 'Proof of Activity', 'Proof of Revenue', 'Proof of Maintenance'],
    specs: [
      { label: 'Metering', value: 'kWh generated/exported' },
      { label: 'Activity proof', value: 'Generation and storage cycles' },
      { label: 'Revenue source', value: 'Energy savings / export' },
      { label: 'Phase', value: 'Post-MVP' },
      { label: 'Primary proof', value: 'Metered energy output' },
    ],
    requirements: ['Energy site KYC', 'Metering data', 'Export or savings report', 'Maintenance plan', 'Grid/offtake documentation'],
  },
] as const

export type RwaAssetCatalogItem = (typeof RWA_ASSET_CATALOG)[number]
