export const RWA_ASSET_CATALOG = [
  {
    id: 'motor-listrik',
    name: 'Motor Listrik',
    category: 'Ojol / Kurir',
    segment: 'Urban Mobility',
    image: '/ev_ridehailing_surabaya_1777118125456.png',
    description:
      'Motor listrik untuk operasi harian ride-hailing dan pengiriman paket B2C dengan revenue harian yang mudah diverifikasi.',
    specs: [
      { label: 'Range per charge', value: '60-120 km' },
      { label: 'Max speed', value: '60-80 km/jam' },
      { label: 'Load capacity', value: '100-150 kg' },
      { label: 'Service interval', value: '2.500 km' },
      { label: 'Useful life', value: '5-7 tahun' },
    ],
    requirements: ['Min. 1 unit', 'KYC operator aktif', 'GPS device terpasang', 'SLA operasional harian'],
    apy: '12-18%',
    pricePerShare: 30000,
    minFleet: 1,
  },
  {
    id: 'motor-kargo',
    name: 'Motor Kargo Listrik',
    category: 'Logistik / Kurir',
    segment: 'Last-mile Delivery',
    image: '/ev_logistics_bandung_1777118107682.png',
    description:
      'Motor kargo listrik untuk last-mile delivery, dark store, dan logistik gudang urban dengan jadwal operasional padat.',
    specs: [
      { label: 'Range per charge', value: '50-100 km' },
      { label: 'Max speed', value: '50-70 km/jam' },
      { label: 'Load capacity', value: '150-200 kg' },
      { label: 'Service interval', value: '2.500 km' },
      { label: 'Useful life', value: '4-6 tahun' },
    ],
    requirements: ['Min. 5 unit', 'KYC bisnis', 'GPS device terpasang', 'Kontrak logistik aktif'],
    apy: '10-16%',
    pricePerShare: 30000,
    minFleet: 5,
  },
  {
    id: 'mobil-listrik',
    name: 'Mobil Listrik',
    category: 'Korporat',
    segment: 'Corporate Fleet',
    image: '/ev_fleet_jakarta_1777118073477.png',
    description:
      'Kendaraan listrik roda empat untuk armada korporat, ride-hailing premium, dan pool kendaraan perusahaan.',
    specs: [
      { label: 'Range per charge', value: '200-400 km' },
      { label: 'Max speed', value: '100-150 km/jam' },
      { label: 'Capacity', value: '4-5 penumpang' },
      { label: 'Service interval', value: '5.000 km' },
      { label: 'Useful life', value: '7-10 tahun' },
    ],
    requirements: ['Min. 3 unit', 'KYC bisnis (PT)', 'GPS + telematics aktif', 'Asuransi kendaraan'],
    apy: '8-14%',
    pricePerShare: 45000,
    minFleet: 3,
  },
  {
    id: 'van-listrik',
    name: 'Van Listrik',
    category: 'Logistik',
    segment: 'Mid-mile Logistics',
    image: '/ev_fleet_tangerang_1777118150818.png',
    description:
      'Van listrik untuk pengiriman volume besar, catering, dan logistik mid-mile yang membutuhkan utilisasi stabil.',
    specs: [
      { label: 'Range per charge', value: '150-300 km' },
      { label: 'Max speed', value: '90-120 km/jam' },
      { label: 'Load capacity', value: '500-1.000 kg' },
      { label: 'Service interval', value: '5.000 km' },
      { label: 'Useful life', value: '7-10 tahun' },
    ],
    requirements: ['Min. 3 unit', 'KYC bisnis', 'GPS terpasang', 'Kontrak logistik aktif'],
    apy: '9-15%',
    pricePerShare: 50000,
    minFleet: 3,
  },
  {
    id: 'truk-listrik',
    name: 'Truk Listrik',
    category: 'Logistik',
    segment: 'Distribution',
    image: '/ev_fleet_tangerang_1777118150818.png',
    description:
      'Truk listrik untuk distribusi barang antar kota jarak menengah dengan kontrak operasional B2B.',
    specs: [
      { label: 'Range per charge', value: '200-400 km' },
      { label: 'Max speed', value: '80-100 km/jam' },
      { label: 'Load capacity', value: '3-8 ton' },
      { label: 'Service interval', value: '7.500 km' },
      { label: 'Useful life', value: '10-15 tahun' },
    ],
    requirements: ['Min. 2 unit', 'KYC bisnis (PT)', 'GPS + telematics', 'Izin angkutan barang'],
    apy: '8-13%',
    pricePerShare: 75000,
    minFleet: 2,
  },
  {
    id: 'bus-listrik',
    name: 'Bus Listrik',
    category: 'Korporat',
    segment: 'People Movement',
    image: '/ev_fleet_jakarta_1777118073477.png',
    description:
      'Bus listrik untuk angkutan karyawan korporat, wisata, dan antar-jemput pabrik dengan kontrak pendapatan reguler.',
    specs: [
      { label: 'Range per charge', value: '200-350 km' },
      { label: 'Max speed', value: '80-100 km/jam' },
      { label: 'Capacity', value: '20-50 penumpang' },
      { label: 'Service interval', value: '10.000 km' },
      { label: 'Useful life', value: '10-15 tahun' },
    ],
    requirements: ['Min. 2 unit', 'KYC bisnis (PT)', 'GPS + telematics', 'Izin angkutan penumpang', 'Kontrak korporat aktif'],
    apy: '7-12%',
    pricePerShare: 100000,
    minFleet: 2,
  },
] as const

export type RwaAssetCatalogItem = (typeof RWA_ASSET_CATALOG)[number]
